#!/usr/bin/env bash
# Full deploy: backend zips → terraform apply → frontend build → S3 sync → CloudFront invalidation.
#
# Usage: ./deploy.sh [--profile DIR] [-auto-approve]
#
# Everything deployment-specific lives in the profile directory, never in this repo:
#   DIR/cabin.config.json   branding and message copy (required)
#   DIR/terraform.tfvars    project name, region, custom domain (required)
#   DIR/backend.hcl         S3 remote state config (optional; local state if absent)
#   DIR/terraform.tfstate   local state, used only when backend.hcl is absent
#   DIR/public/             optional static files overlaid onto the built site
#
# Defaults to ./profile.example so the repo deploys standalone.
set -euo pipefail
cd "$(dirname "$0")"
REPO="$PWD"

PROFILE="$REPO/profile.example"
APPROVE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --profile) PROFILE="$2"; shift 2 ;;
    -auto-approve|--auto-approve) APPROVE="-auto-approve"; shift ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

PROFILE="$(cd "$PROFILE" && pwd)"
CONFIG="$PROFILE/cabin.config.json"
TFVARS="$PROFILE/terraform.tfvars"
TFSTATE="$PROFILE/terraform.tfstate"
BACKEND="$PROFILE/backend.hcl"

for f in "$CONFIG" "$TFVARS"; do
  [ -f "$f" ] || { echo "Missing required profile file: $f" >&2; exit 1; }
done
echo "==> Profile: $PROFILE"

# A backend block cannot take variables, so the choice of remote vs local state
# is made by generating infra/backend.tf (gitignored) from the profile.
if [ -f "$BACKEND" ]; then
  STATE_MODE="remote"
  cat > infra/backend.tf <<'EOF'
# Generated by deploy.sh from the profile's backend.hcl. Do not edit or commit.
terraform {
  backend "s3" {}
}
EOF
  INIT_ARGS=(-backend-config="$BACKEND")
  STATE_ARGS=()

  # Refuse to silently begin from an empty remote state while real local state
  # still exists — that would orphan every deployed resource.
  if [ -s "$TFSTATE" ] && [ "$(python3 -c 'import json,sys;print(len(json.load(open(sys.argv[1])).get("resources",[])))' "$TFSTATE" 2>/dev/null || echo 0)" -gt 0 ]; then
    echo "ERROR: $TFSTATE still holds resources, but backend.hcl selects remote state." >&2
    echo "Migrate it once, then remove the local file:" >&2
    echo "  (cd infra && terraform init -migrate-state -backend-config=\"$BACKEND\" -state=\"$TFSTATE\")" >&2
    exit 1
  fi
else
  STATE_MODE="local"
  rm -f infra/backend.tf
  INIT_ARGS=()
  STATE_ARGS=(-state="$TFSTATE")
fi
echo "==> State: $STATE_MODE"

# The media pipeline (PRD 5.8) needs a CloudFront signing keypair. It is required
# by Terraform and deployment-specific, so generate it on first deploy rather than
# failing the apply — the private half stays in the profile dir and goes to SSM below.
if ! grep -q '^[[:space:]]*media_public_key_pem[[:space:]]*=' "$TFVARS" ||
   grep -q 'REPLACE with the contents of' "$TFVARS"; then
  echo "==> No CloudFront media signing key in this profile — generating one"
  "$REPO/scripts/media-cf-keys.sh" generate --profile "$PROFILE"
  MEDIA_KEY_IS_NEW=1
fi

# Terraform reads this artifact directly; a missing layer fails mid-apply with an
# opaque expression error, so check it here where the fix is obvious.
LAYER_ZIP="$REPO/backend/layers/sharp-heif/dist/layer.zip"
if [ ! -s "$LAYER_ZIP" ]; then
  echo "ERROR: missing $LAYER_ZIP" >&2
  echo "Build it with Docker:  backend/layers/sharp-heif/build.sh" >&2
  echo "Or download the CI-built artifact (see .github/workflows/layer-build.yml)." >&2
  exit 1
fi

echo "==> Building backend Lambda bundles"
# `npm ci` before every build, not just on a fresh checkout. A profile repo pins this repo as a
# submodule, so bumping the pin swaps in a new package.json while leaving the old node_modules in
# place — esbuild then fails to resolve any newly added dependency. That is a confusing failure
# that looks like broken source rather than stale deps, and it also hits a first-ever clone.
# `ci` (not `install`) so the lockfile is authoritative and the tree is reproducible.
(cd backend && npm ci --silent && npm run build)

echo "==> Applying Terraform"
(cd infra \
  && terraform init -input=false -reconfigure "${INIT_ARGS[@]}" >/dev/null \
  && terraform apply -input=false $APPROVE \
       -var-file="$TFVARS" \
       -var="app_config_file=$CONFIG" \
       "${STATE_ARGS[@]}")

tf_out() { (cd infra && terraform output "${STATE_ARGS[@]}" -raw "$1"); }

echo "==> Reading Terraform outputs"
API_URL=$(tf_out api_url)
USER_POOL_ID=$(tf_out user_pool_id)
CLIENT_ID=$(tf_out user_pool_client_id)
BUCKET=$(tf_out site_bucket)
DIST_ID=$(tf_out cloudfront_distribution_id)
SITE_URL=$(tf_out site_url)

# The SSM parameter is created with a placeholder value that Terraform then
# ignores, so the real signing key has to be pushed out-of-band after the apply.
if [ -n "${MEDIA_KEY_IS_NEW:-}" ]; then
  echo "==> Publishing the media signing key to SSM"
  "$REPO/scripts/media-cf-keys.sh" push --profile "$PROFILE" \
    --param "$(tf_out media_cf_private_key_param)"
fi

echo "==> Building frontend"
cat > frontend/.env.production <<EOF
VITE_API_URL=$API_URL
VITE_USER_POOL_ID=$USER_POOL_ID
VITE_CLIENT_ID=$CLIENT_ID
EOF
(cd frontend && npm ci --silent && CABIN_CONFIG="$CONFIG" npm run build)

# Profile-supplied favicons, images, etc. win over the repo defaults.
if [ -d "$PROFILE/public" ]; then
  echo "==> Overlaying profile public/ assets"
  cp -R "$PROFILE/public/." frontend/dist/
fi

echo "==> Uploading site to s3://$BUCKET"
aws s3 sync frontend/dist "s3://$BUCKET" --delete

echo "==> Invalidating CloudFront cache"
aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*" >/dev/null

echo ""
echo "Deployed: $SITE_URL"
